
import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { ModeProvider } from "./contexts/ModeContext";
import RootComponent from "./components/RootComponent";

export const metadata: Metadata = {
  title: "Krea App",
  description: "Generated by Next.js",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // Add suppressHydrationWarning to the <html> tag
    <html lang="en" suppressHydrationWarning>
      <body className={`w-full ${montserrat.variable} antialiased`}>
        <ModeProvider>
          <RootComponent>{children}</RootComponent>
        </ModeProvider>
      </body>
    </html>
  );
}